### ISSUE TITLE
AutoSnappingController.setSensitivity

### ISSUE THREAD

**Issue by menno-m** [doo/Scanbot-SDK-Examples#17]
Hi,

The documentation at http://doo.github.io/Scanbot-SDK-Documentation/Android/ mentions a AutoSnappingController.setSensitivity method but in io.scanbot:sdk-package-1:1.18.4 i cannot find it. Is it removed?

Thank you in advance

**Comment by dmitry-zaitsev** [comment]
Hi,

No, method is still there. Note that this is **not** a static method, perhaps that's why you can't find it.
Here's an example:

    AutoSnappingController controller = AutoSnappingController.attach(cameraView, contourDetectorFrameHandler);
    controller.setSensitivity(0.5f);

**Comment by menno-m** [comment]
Thank you, found it
