### ISSUE TITLE
MagnifierView only works in Activity?

### ISSUE THREAD

**Issue by menno-m** [doo/Scanbot-SDK-Examples#18]
Hi,

I am experimenting with the example code from "edit-polygon-view". I am trying to make it work in a fragment instead of in an activity. I can only get it working if my activity implements the DrawMagnifierListener interface and then passes the calls through to the fragment. 

Maybe this could be an improvement as one could want to put the functionality in a Fragment. Or maybe i am doing something wrong ;)

**Comment by dmitry-zaitsev** [comment]
Hi @menno-m 

Would be great if you will share the sample code with us.

**Comment by menno-m** [comment]
Here i have the example modified to use the MagnifierView in a fragment instead of activity.
To make it work i have to let the activity implement DrawMagnifierListener interface and then passes the calls through to the fragment, which is not desired i guess...

[ScanbotSDKexample_MagnifierInFragment.zip](https://github.com/doo/Scanbot-SDK-Examples/files/493253/ScanbotSDKexample_MagnifierInFragment.zip)

**Comment by dmitry-zaitsev** [comment]
@menno-m 

There is indeed a bug on our side - currently `MagnifierView` works only if your `Activity` implements `DrawMagnifierListener` and delegates calls to `MagnifierView` (either directly or through the `Fragment` as in your case). That's is certainly not great, so we will fix it.

**Comment by dmitry-zaitsev** [comment]
Please try the new version of the SDK - `1.19.0`

We removed `DrawMagnifierListener` completely. Now it's enough to just call `setupMagnifier`.
