### ISSUE TITLE
Cannot debug

### ISSUE THREAD

**Issue by lnicolet** [doo/Scanbot-SDK-Examples#20]
I started using this SDK. Everything works fine, I downloaded examples and I'm developing my own application in which I use `ScanbotCameraView` and `PolygonView` to help the user see what he's capturing. However, I would like to have the photo taken automatically when something's recognized, and I can reach that by using `AutoSnappingController` but I noticed it's slow. In your examples, you use a `onClickListener` of a `Button` to take the picture. What I would like to do is that if the use clicks the snap button and there isn't a `PolygonView` visible, the application shows a `Toast` to the user saying it's better to have the document selected by the `PolygonView`.
I'm using an if statement, but it seems it's not working, and I can't reach the debugger, the application is always stuck in "waiting for debugger to attach". Any suggestion?

**Comment by lnicolet** [comment]
Well, thanks for the support! Closing a issue without even trying to resolve it!

**Comment by eddyfrank** [comment]
Hi @lnicolet ,

sorry, it was an oversight. I just reopened it and we are checking it...

Regards,
Eddy

**Comment by eddyfrank** [comment]
> What I would like to do is that if the use clicks the snap button and there isn't a PolygonView 
> visible, the application shows a Toast to the user saying it's better to have the document 
> selected by the PolygonView.

You could handle it in the `onPictureTaken(..)` method using detected polygon from `ContourDetector` class, like:

```
@Override
public void onPictureTaken(byte[] image, int imageOrientation) {
    BitmapFactory.Options options = new BitmapFactory.Options();
    options.inSampleSize = 4; // use 1 for original size (if you want no downscale)!!
                              // in this demo we downscale the image to 1/4 for the preview.
    Bitmap originalBitmap = BitmapFactory.decodeByteArray(image, 0, image.length, options);

    // Run document detection on original image:
    ContourDetector detector = new ContourDetector();
    detector.detect(originalBitmap);
    List<PointF> polygon = detector.getPolygonF();
    if (polygon.isEmpty()) {
        this.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Toast.makeText(MainActivity.this, "Your message...", Toast.LENGTH_SHORT).show();
                cameraView.continuousFocus();
                cameraView.startPreview();
            }
        });
    } else {
        final Bitmap documentImage = detector.processImageAndRelease(originalBitmap, polygon, ContourDetector.IMAGE_FILTER_NONE);
        resultView.post(new Runnable() {
            @Override
            public void run() {
                resultView.setImageBitmap(documentImage);
                cameraView.continuousFocus();
                cameraView.startPreview();
            }
        });
    }
}
```

**Comment by lnicolet** [comment]
That could be a solution! Thanks, I will try it whenever I'll be on that project again.
What about the problem of the debug? My phones weren't able to connect to the debug process

**Comment by Kubiria** [comment]
Hi @lnicolet ,

Please, make sure that you are using build variant "debug" for your installed app and it should be running on the device. Also device reboot and "adb" restart could help to solve this problem.
For "adb" restart try to switch off and on Tools -> Android -> Enable ADB Integration option in Android Studio. Or "adb kill-server" and "adb start-server" commands in Terminal.

Hope this tips will solve your problem.

Best regards,
Artem

**Comment by eddyfrank** [comment]
This issue will be closed because there hasn't been any activity for a few months.
Feel free to open a new one if you still experience this problem.
