### ISSUE TITLE
setRequestedOrientation(...) makes Scanbot leak the hosting activity

### ISSUE THREAD

**Issue by menjoo** [doo/Scanbot-SDK-Examples#22]
Hi,

I found that if you put `setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);` in onCreate of the hosting activity, The camera view keeps a reference to the activity. Since setting the orientation this way destroys the activity right away and then recreates it, the activity is leaked. 

You can reproduce the leak like this: 

- In your camera-view example project in MainActivity.onCreate add`setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);`
- Run it
- Open the activity, then finish it
- Dump memory and run the analyzer tasks in Android Studio.
- It shows one leak for each time its started and finished.

I know you can also achieve setting the orientation in the manifest, i tried, that way it does not leak.

Regards,

Menno Morsink
ING

**Comment by JovianEvan** [comment]
@ @ #76 #75 #75 #76

**Comment by Kubiria** [comment]
Issue is no reproducible.
Please try the latest version of the SDK.
