### ISSUE TITLE
Added trial license crashes immediately

### ISSUE THREAD

**Issue by airballdigital** [doo/Scanbot-SDK-Examples#25]
I add the trial license code to the manifest as shown in examples and it crashes immediately. What could be missing? I am testing on an actual device but it crashes on emulator as well. The application isn't in the google play store yet.

**Comment by Kubiria** [comment]
Hi, unfortunately there's not enough information, please contact us at sdk@scanbot.io and add crash log if possible. Thank you for your feedback.
