### ISSUE TITLE
Scaletype seems not to work on EditPolygonImageView

### ISSUE THREAD

**Issue by Runman44** [doo/Scanbot-SDK-Examples#29]
When I implement an Imageview in a EditPolygonImageView it will not scale the image to fit the screen.

I already set the scaletype of the EditPolygonImageView to fitCenter but the image inside it seems to ignore this. 

Can you confirm this is an issue? I will keep researching.

**Comment by eddyfrank** [comment]
Hi @Runman44
Could you provide some example code please. I don't get your intention.

I successfully tested it with
```
editPolygonView.setScaleType(ImageView.ScaleType.FIT_CENTER);
```
and
```
editPolygonView.setScaleType(ImageView.ScaleType.CENTER_CROP);
```

**Comment by Runman44** [comment]
Hey Eddy ! Sorry about the issue, this wasn't the fault of Scanbot but my own lack of knowledge about transformations in Views. 

I noticed that the scanbot App - scales the image after rotation 90 degrees. I wonder how you guys tackled this issue

I've opened a stackoverflow question. Maybe you guys can help me with my own issue on the stackoverflow page, this issue can be closed I guess :)
