### ISSUE TITLE
continuousFocus()

### ISSUE THREAD

**Issue by Bertkiing** [doo/Scanbot-SDK-Examples#32]
mCameraView.continuousFocus() is replaced by cameraView.autoFocus()?

**Comment by Kubiria** [comment]
No, there are both of them now in CameraView.
cameraView.autoFocus() - performs auto-focus on the center of the image once.
cameraView.continuousFocus() -  camera continuously tries to focus. https://github.com/doo/Scanbot-SDK-Examples/wiki/Using-ScanbotCameraView#enable-continuous-focus-mode
