### ISSUE TITLE
The EditPolygonImageView cannot ContourDetector

### ISSUE THREAD

**Issue by Bertkiing** [doo/Scanbot-SDK-Examples#33]
[Using EditPolygonImageView](https://github.com/doo/Scanbot-SDK-Examples/wiki/Using-EditPolygonImageView) is too simple to useless

**Comment by eddyfrank** [comment]
Hi @Bertkiing 

What is the actual issue with `EditPolygonImageView`?
Could you please describe it in detail? 
Thx!

**Comment by Bertkiing** [comment]
Thanks for your reply!!!
I'm so sorry that I just follow the example to use the EditPolygonImageView, but not reach my wanted effect.
For example:
![test](https://user-images.githubusercontent.com/19733128/26861515-efcf824a-4b76-11e7-91b6-d8cc5b7c4f2b.jpg)

**Comment by Bertkiing** [comment]
BTW，why the ScanbotCamera only on the case that having a polygon can take a picture . On the contrary 
, it's no response

**Comment by eddyfrank** [comment]
Hi @Bertkiing,

please contact us via sdk@scanbot.io.

Thanks.

Regards,
Eddy
