### ISSUE TITLE
Error: D/OCR: Default language is not available - abort OCR: ENG

### ISSUE THREAD

**Issue by tangzhou711** [doo/Scanbot-SDK-Examples#38]
- AndroidManifest.xml
meta-data android:name="ocr_blobs_path" android:value="my_traineddata/"

and used local assets files for ocr.

- assets/my_traineddata/
  + eng.traineddata
  + osd.traineddata,
  + pdf.ttf

**Comment by eddyfrank** [comment]
Even if the OCR files are stored as local files you have to "fetch" them:

`blobManager.fetch(blob, false);` 

See https://github.com/doo/Scanbot-SDK-Examples/blob/master/ScanbotSDKexample/ocr/src/main/java/io/scanbot/example/MainActivity.java#L134 for full fetch example code.

By "fetching" the Scanbot SDK will copy the OCR blob files from assets directory to an internal working directory.
