### ISSUE TITLE
Runtime Error: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by jchavarria1983** [doo/Scanbot-SDK-Examples#39]
Hi, I created an app and use the scanbot sdk plugin,  I tested it in a lot of devices and it works fine but when I tested in Samsung S6 Edge Android 7.0 the app crashed.

I got the runtime error logs:

AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.app-2/lib/arm64, /data/app/com.app-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libsap.so"
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:972)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1567)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at io.scanbot.sap.SapManager.<clinit>(SapManager.java:23)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at net.doo.snap.c.c.b(SourceFile:36)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at net.doo.snap.c.c.a(SourceFile:27)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at net.doo.snap.c.a.a(SourceFile:24)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at net.doo.snap.b.k.a(SourceFile:117)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at net.doo.snap.b.w.get(SourceFile:1026)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at net.doo.snap.b.j.b(SourceFile:383)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at net.doo.snap.ScanbotSDK.<init>(SourceFile:67)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at net.doo.snap.ScanbotSDK.<init>(SourceFile:49)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at io.scanbot.sdk.plugin.cordova.ScanbotSdkWrapper$PdfSdk.<init>(ScanbotSdkWrapper.java:343)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at io.scanbot.sdk.plugin.cordova.ScanbotSdkPlugin$1.run(ScanbotSdkPlugin.java:167)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6682)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
07-27 15:04:03.388 23429 23429 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

Could anyone help me to find the solution ? It seems like a missing library.

**Comment by eddyfrank** [comment]
Hi @jchavarria1983 ,

did you adjust the ABI settings accordingly?
Please see https://github.com/doo/Scanbot-SDK-Examples/wiki/Getting-started#abi-settings

Regards,
Eddy
