### ISSUE TITLE
SCANBOT_SDK_LICENSE_KEY

### ISSUE THREAD

**Issue by Angsus17** [doo/Scanbot-SDK-Examples#4]
How I can get a license?

    <meta-data android:name="SCANBOT_SDK_LICENSE_KEY" android:value="Insert your key here" />

**Comment by dmitry-zaitsev** [comment]
@Angsus17 
Please contact us at sdk@scanbot.io

**Comment by dmitry-zaitsev** [comment]
@Angsus17 
We just updated our SDK, so now it has free trial period. Just skip license-key part in `AndroidManifest` and example app will work for 1 minute.
