### ISSUE TITLE
Error:Failed to resolve: io.scanbot:payformscanner.lib:1.0.2

### ISSUE THREAD

**Issue by mvsiva4u** [doo/Scanbot-SDK-Examples#40]
I'm getting below Error. while running the application getting the below error.

Error:Failed to resolve: io.scanbot:payformscanner.lib:1.0.2.

Please help me to resolve. This is happening while running application for android.

**Comment by Kubiria** [comment]
Issue is fixed. Please, try to pull the latest changes from master branch.
