### ISSUE TITLE
Storing default blobs locally and downloading others from main

### ISSUE THREAD

**Issue by 301shevchukanton** [doo/Scanbot-SDK-Examples#48]
I want to have few default languages in assets and some others downloadable from Internet. 
How can I achieve it?

**Comment by 301shevchukanton** [comment]
I've found a way to do it by modifying Blobs objects. I modify a remotePath for those, which one are not in my assets and are not system one.

**Comment by eddyfrank** [comment]
Alternatively, you can get the final (internal) target directory for OCR blobs from the SDK (`new ScanbotSDK(..).blobManager().getOCRBlobsDirectory()`) and implement a custom mechanism to put the blobs files into it.
