### ISSUE TITLE
Meaningless/default parameter names such as 'p0'

### ISSUE THREAD

**Issue by tlhintoq** [doo/Scanbot-SDK-Examples#53]
According to the documentation I've read, the nuget is really a binding library around the java jar.
Any chance of applying transforms to the binding lib so we can have meaningful parameter names instead of 'p0', 'p1' and so on?
![image](https://user-images.githubusercontent.com/11351506/37931072-84be5d82-3112-11e8-93cf-e6ace03cb16e.png)

For example (these come from binding lib I put together for another vendor's USB scanner driver/jar)
```xml
    <attr path="/api/package[@name='pdi.android']/interface[@name='pdiscan.callback']/method[@name='ScanningError']/parameter[@name='p0']"
          name="name">errorNumber</attr>
    <attr path="/api/package[@name='pdi.android']/interface[@name='pdiscan.callback']/method[@name='ScanningError']/parameter[@name='p1']"
          name="name">errorMessage</attr>
```
Having meaningful intellisense popup does wonders for making the SDK "developer friendly"

**Comment by tailsu** [comment]
That's a good idea! Thanks for reaching out to us. We just need to disable the removal of parameter names by proguard. Then the bindings generator will pick up the names using reflection.

I've added an issue to our bugtracker.

**Comment by eddyfrank** [comment]
Fixed in the new Xamarin nuget package `ScanbotSDK.Xamarin`: https://www.nuget.org/packages/ScanbotSDK.Xamarin
