### ISSUE TITLE
Bitmap.LockPixels() on returned bitmap from DocumentDetection throws exception

### ISSUE THREAD

**Issue by tlhintoq** [doo/Scanbot-SDK-Examples#54]
If I try to `LockPixels()` on the original bitmap shot there is no problem.
Try the same call on the result bitmap from `SBSDK.DocumentDection` throws a System.ArgumentException.
Drilling down it looks like the `.GetWidth()` method returns null.
![image](https://user-images.githubusercontent.com/11351506/38056428-6666ea36-32aa-11e8-8df2-b0d6f6ebd735.png)

![image](https://user-images.githubusercontent.com/11351506/38056468-7f30d5b8-32aa-11e8-95eb-28720de30e62.png)

**Comment by tlhintoq** [comment]
Issue was caused elsewhere - not in SDK

**Comment by tailsu** [comment]
`detectionResult.Image` is just a regular Bitmap. There's nothing that we do to make it invalid like that. The reason for the crash is lies somewhere else.
