### ISSUE TITLE
Google play service

### ISSUE THREAD

**Issue by jackhui** [doo/Scanbot-SDK-Examples#59]
Does the scanbot use any component from Google play service? Since my app includes mobile vision,  there is a version conflict of Google play service in my project after scanbot sdk is added. Is it possible to change the version of Google Play service in the Scanbot SDK?

**Comment by eddyfrank** [comment]
Yes, Scanbot SDK uses Google Play Services.
You can `force` to certain version of Google libs in your project (`app/build.gradle`), like:
```
configurations.all {
   resolutionStrategy {
       force group: 'com.google.android.gms', name: 'play-services-vision', version: 'x.x.x'
   }
}
```
