### ISSUE TITLE
Mute the shutter sound

### ISSUE THREAD

**Issue by DanteAndroid** [doo/Scanbot-SDK-Examples#66]
# Muting the shutter sound

## Known Issue

In some models like XIAOMI, LePhone, the shutter sound cannot be muted.

## Tried methods

- The cameraView.setShutterSound eventaully called Camera.enableShutterSound which returns false (means that shutter sound cannot be disabled) in XIAOMI
- Using AudioManaer to adjust AudioManager.STREAM_SYSTEM to mute system sound, not working.

## Possible solution

The ScanbotCameraView in Scanbot SDK is using Camera API which is deprecated, Google recommends using Camera2. 

We ran Camera2 demo in XIAOMI to find that it has no shutter sound (BTW you can implement it in CameraCaptureSession.CaptureCallback's onCaptureStarted)

We think it is better to upgrade the Scanbot SDK with Camera2 API.

**Comment by eddyfrank** [comment]
Fixed in the latest SDK version **1.31.1**.
See release notes: https://github.com/doo/Scanbot-SDK-Examples#1311
