### ISSUE TITLE
CameraView is black when return

### ISSUE THREAD

**Issue by DanteAndroid** [doo/Scanbot-SDK-Examples#72]
When we leave the capture activity and return, the CameraView is black. CameraView.onPause() and onResume is properly handled.
The bug only happens in XIAOMI models so far.

**Comment by jaimefdml** [comment]
Same issue with Mitac ruggedized tablets.

**Comment by tailsu** [comment]
We are currently working on a fix for Xiaomi.

@jaimefdml, which Mitac model have you tested on?

**Comment by eddyfrank** [comment]
Fixed in the latest release **v1.37.0**. 
See the changelog https://github.com/doo/Scanbot-SDK-Examples#1370
