### ISSUE TITLE
Having an issue with latest version of android support libraries.

### ISSUE THREAD

**Issue by RingoMckraken** [doo/Scanbot-SDK-Examples#75]
Just trying to have a successful project build. Currently build fails with the following message:

Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
AGPBI: {"kind":"error","text":"Program type already present: androidx.core.graphics.PathSegment","sources":[{}],"tool":"D8"}

**Comment by tailsu** [comment]
Apparently you're linking more than one version of the support libraries - don't do that :)

**Comment by RingoMckraken** [comment]
does the scanbot sdk play nicely with androidX dependencies?

**Comment by RingoMckraken** [comment]
That is basically what I'm trying to figure out. I started a base java project in the canary version of Android Studio with default imports and upon following the start-up guide here for including Scanbot package 1 with a basic camera view it gives the error above.

**Comment by tailsu** [comment]
Can you post the entire build.gradle of the project?

**Comment by RingoMckraken** [comment]
Sure Thing:

Project Level
`   
    buildscript {
        
        repositories {
            google()
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:3.3.0-alpha05'
        }
    }
    
    allprojects {
        repositories {
            google()
            jcenter()
            maven {
                url 'https://nexus.scanbot.io/nexus/content/repositories/releases/'
            }
            maven {
                url 'https://nexus.scanbot.io/nexus/content/repositories/snapshots/'
            }
        }
    }
    
    task clean(type: Delete) {
        delete rootProject.buildDir
    }

`

App Module:
`    
    apply plugin: 'com.android.application'
    
    android {
        compileSdkVersion 28
        buildToolsVersion "28.0.2"
        defaultConfig {
            applicationId "com.ringodev.scantest"
            minSdkVersion 22
            targetSdkVersion 28
            versionCode 1
            versionName "1.0"
            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
            ndk {
                abiFilters "armeabi-v7a", "arm64-v8a", "x86"
            }
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            }
        }
    }
    
    dependencies {
        implementation fileTree(dir: 'libs', include: ['*.jar'])
        implementation 'androidx.appcompat:appcompat:1.0.0-rc01'
        implementation 'androidx.constraintlayout:constraintlayout:1.1.2'
        implementation 'com.google.android.material:material:1.0.0-rc01'
        implementation 'io.scanbot:sdk-package-1:1.33.3'
        testImplementation 'junit:junit:4.12'
        androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
        androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'
    }
`

**Comment by tailsu** [comment]
So the new AndroidX support libraries definitely cause conflicts with the old ones. We still use the com.android.support group of modules and namespaces.

I suggest you use the gradle files in this repo as a starting point for your project. More importantly use the dependency versions used in this project.

Is using AndroidX a requirement for you?

**Comment by RingoMckraken** [comment]
Thank you for the feedback, changing the dependencies to the old support library namespace definitely works. For my current project, AndroidX is not a requirement, but it does appear that Android Studio is begin to default to using that namespace at least in the canary version and most likely soon to be in the stable version. Google seems to be very aggressive as of late when it comes to "strongly suggesting" certain patterns haha!

**Comment by RingoMckraken** [comment]
I guess we can consider this resolved I'll go ahead and close this for now. Thanks again!

**Comment by tailsu** [comment]
All right. We'll migrate to the AndroidX support library some time *after* it comes out beta. Until then, et kütt wie et kütt.
