### ISSUE TITLE
Gradle issue

### ISSUE THREAD

**Issue by kumar5572** [doo/Scanbot-SDK-Examples#78]
After adding all the gradle lines facing the issue like **Program type already present: org.apache.commons.codec.BinaryDecoder** how can i solve this...

**Comment by lebedevsd1** [comment]
Hello @kumar5572 seems like there are the conflict in your dependencies. 
Please follow the instructions provided here [link](https://stackoverflow.com/a/49767860/2045644)

**Comment by eddyfrank** [comment]
We haven't received a response to this issue and are assuming that this is solved.
