### ISSUE TITLE
onActivityResult Intent payload for DocumentScannerActivity

### ISSUE THREAD

**Issue by sschendel** [doo/Scanbot-SDK-Examples#80]
I'm struggling to find reference to the structure of the payload returned by "ready to run UI" component DocumentScannerActivity.

The Sample app just launches a preview activity which reads scanned pages from some PageStorage persistence.

https://github.com/doo/Scanbot-SDK-Examples/blob/master/ScanbotSDKexample/ready-to-use-ui/src/main/java/io/scanbot/example/MainActivity.java#L74

I'm assuming the DocumentScannerActivity response intent holds some information on the captured scan.  I can see it holds a ParcelableArray in key: `DocumentScannerActivity.SNAPPED_PAGE_EXTRA`, but I can't find any documentation describing what the structure is.

**Comment by eddyfrank** [comment]
The result playload is a parcelable array of `Page`s (`io.scanbot.sdk.persistence.Page`):

```
@Override
protected void onActivityResult(final int requestCode, final int resultCode, final Intent data) {
    if (requestCode == XXX && resultCode == RESULT_OK) {
        final Parcelable[] parcelablePages = data.getParcelableArrayExtra(DocumentScannerActivity.SNAPPED_PAGE_EXTRA);
        for (final Parcelable p: parcelablePages) {
            final Page page = (Page) p;
            final Uri previewImageUri = scanbotSDK.pageFileStorage().getPreviewImageURI(page.getPageId(), PageFileStorage.PageFileType.DOCUMENT)
        }
    }
}
```

@sschendel , thanks for your report. We will add it to our docs and examples.

**Comment by sschendel** [comment]
Thanks, that's what I thought but I was failing using wrong type at first.
`import net.doo.snap.entity.Page`
Working now. Thank you.
